### ISSUE TITLE
Some Malayalam URLs are not accepted

### ISSUE THREAD

**Issue by svbergerem** [markdown-it/linkify-it#10]
http://lyricstranslate.com/en/someone-you-നിന്നെ-പോലൊരാള്‍.html is a correct URL but linkify-it cuts off the last characters. We are currently using markdown-it 3.1.0 for diaspora* which has no problems with this URL so I think this could be even a regression. (3.1.0 was the first version that used linkify-it)

**Comment by puzrin** [comment]
You can use demo permalinks for simplicity: [this example](http://markdown-it.github.io/linkify-it/#t1=http%3A%2F%2Flyricstranslate.com%2Fen%2Fsomeone-you-%E0%B4%A8%E0%B4%BF%E0%B4%A8%E0%B5%8D%E0%B4%A8%E0%B5%86-%E0%B4%AA%E0%B5%8B%E0%B4%B2%E0%B5%8A%E0%B4%B0%E0%B4%BE%E0%B4%B3%E0%B5%8D%E2%80%8D.html%0A)

You are right. Problem is in https://github.com/markdown-it/linkify-it/commit/2eaa49273163f4446849d97778747e2c3c7560ae. Adding `Cf` class to "bad chars" was a mistake, caused by my wrong understanding of unicode. 

Thanks for good example! Feedback from you team helps a lot to polish markdown-it & linkify-it.

**Comment by svbergerem** [comment]
Awesome! Thank you for the quick response. :)

**Comment by Flaburgan** [comment]
Wow man, that was quick!
