### ISSUE TITLE
Handling of URLs embedded in <>

### ISSUE THREAD

**Issue by heelhook** [markdown-it/linkify-it#26]
Linkify-it doesn't properly handle links embedded in `<>` properly.

`<http://google.com>` ⨂

While it does handle variations of that format properly:

![linkify-it_demo](https://cloud.githubusercontent.com/assets/779813/11716769/8086ddfc-9f4c-11e5-9f85-8d6ee4d7d5a6.png)

**Comment by puzrin** [comment]
Need to think how to arrange this. That's not a problem in markdown, because `<...>` means autolinking there.

Anyway, your example is reasonable. Could you add more details?

- when this pattern happens in your texts?
- do you know when applying this pattern can become a problem? (i mean,  `<` & `>` in query string and so on)

**Comment by puzrin** [comment]
Not sure that `< >` comes in pairs like `(..)` & `[..]`. So we could really break some links with `>` with changes. Or do links with `>` exists at all?

I could suggest such kludge: if `http(s)://` is prepended with `<`, then drop in found link everything after `>`. But not sure how safe is it.

**Comment by puzrin** [comment]
@svbergerem could you look at this change (strictly disable `<` & `>` inside of linkified slices).

Looks good for me, but may be you have breaking samples.

**Comment by puzrin** [comment]
Released in 1.2.4

**Comment by svbergerem** [comment]
@puzrin Sorry for the late response. I don't have any failing examples. I'll let you know if there is any feedback from users once we are using v1.2.4.
