### ISSUE TITLE
Unexpected URL matching when quotes are involved

### ISSUE THREAD

**Issue by elado** [markdown-it/linkify-it#42]
```json
{"url":"http://www.blah.com/","hello":"world"}
```

URL text match is `http://www.blah.com/","hello":"world` but the `href` is `http://www.blah.com/` (as it should be).

(tested here: http://markdown-it.github.io/linkify-it/)

**Comment by puzrin** [comment]
If you add space after `,` it will work properly. I don't think it worth to care much about any machine-generated strings. This package is for links in human-readable texts.

**Comment by puzrin** [comment]
Look what happens after your sample is formatted to more human-friendly form:

http://markdown-it.github.io/linkify-it/#t1=%7B%20%22url%22%3A%22http%3A%2F%2Fwww.blah.com%2F%22%2C%20%22hello%22%3A%22world%22%20%7D

What do you think? I tend to close.

**Comment by elado** [comment]
@puzrin generally you're right on JSON; I still think it's a bug, with (uncommon) strings like

```
http://www.blah.com/"abc"
```

If `"` cannot be a part of a link, it should stop matching.
The href doesn't match what's highlighted because it's being closed by a quote and the rest becomes an attribute which is unsafe. So that should probably be escaped.

```html
<a target="_blank" href="http://www.blah.com/" abc""="">http://www.blah.com/"abc"</a>
```

Human readable strings are the correct target, until someone tries to inject XSS 🤔

**Comment by puzrin** [comment]
`"` CAN be a part of link sometime: `http://foo.com/blah_blah_"doublequoted"`. That's true for some wiki links and so on. See examples in demo.

**Comment by elado** [comment]
http://markdown-it.github.io/linkify-it/#t1=http%3A%2F%2Fwww.blah.com%2F%22onmouseover%3Dalert(1)%2F%2F%22%0A

That's a serious XSS 😢

**Comment by puzrin** [comment]
Looks like escaping problem in markdown, not in this package. Thanks for report.

**Comment by puzrin** [comment]
Ahh... wrong alarm. Everything is fine with markdown: [demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22http%3A%2F%2Fwww.blah.com%2F%5C%22onmouseover%3Dalert%281%29%2F%2F%5C%22%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

This example works ONLY in linkify-it demo, because nobody cares there about security - demo was done quick and dirty to visualize how linkify-it works. That does not affect package security anyhow.

So, let's return to first post - i thing there are no easy way to understand ton formatted JSON. `"` can happen in wiki links. I think issue can be closed as "artificial".

**Comment by puzrin** [comment]
any thought? I tend to close as "not a bug"

**Comment by elado** [comment]
As long as it's not a parsing problem and quotes are allowed in URLs, it's indeed not a bug because the string I posted couldn't be parsed otherwise.
